### ISSUE TITLE
Support the new api

### ISSUE THREAD

**Issue by kevinsimper** [caitp/node-mock-stdin#15]
The new `process.stdin` uses a different api.

`process.stdin.read()`

Should that be supported?

**Comment by caitp** [comment]
Absolutely. Was this introduced in iojs, or node 0.12 or something?

**Comment by kevinsimper** [comment]
It was introduced in 0.12

The docs shows it and I have already made a working mock of it :)

**Comment by caitp** [comment]
Cool. Would you be willing to submit a pull request?

**Comment by matthewmueller** [comment]
@kevinsimper you still have the code for this? a PR would be appreciated

**Comment by kevinsimper** [comment]
I ended up hacking it out pretty bad https://github.com/blackbeardapp/docker-machine-export/blob/master/tests/unit.js#L27-L37
