### ISSUE TITLE
Not inserting any text into STDIN

### ISSUE THREAD

**Issue by Berkmann18** [caitp/node-mock-stdin#19]
I'm trying to mock STDIN inputs that would normally be done by a user but whenever I'm reading from the STDIN, nothing is in it.
Here's the _minimal_ code:
```js
const readline = require('readline'),
  stdin = require('mock-stdin').stdin();

const readIn = () => {
  info('Press CTRL+D (or CMD+D or using `C` instead of `D`) to stop the STDIN reader\nType either \\$ or \\EOF in an empty line to signal an End-Of-File (this line won\'t be counted)');
  let rl = readline.createInterface({
      input: process.stdin,
      output: process.stdout,
      terminal: false
    }),
    EOF = (str) => str === '\\$' || str === '\\EOF',
    lines = [];

  rl.on('line', (line) => {
    dbg('Found line=', line);
    if (EOF(line)) {
      info('Done');
    } else lines.push(line);
  });

};

const start = () => {
  stdin.send('const greeter = (name) => console.log(`Hello ${name}!`);');
  stdin.send('\$');
  stdin.end();
  readIn();
};

start();
```

I tried combining the minimal code from `readIn()` (taken from a longer version from a package I'm working on) and merge it to the `stdin.[...]()` lines swapping things around but it still reads nothing.
Regardless of whether the `input` field is set to `process.stdin` or `stdin` (even with the `stdin.send('\$');` removed which is how the package nows that the user finished typing some code before entering something else or quitting).

By the way, the `readIn` function works fine with **real** input but not in this scenario or when I was testing with jest.

**Comment by caitp** [comment]
Your demo does what you want it to do, but you need to set up your stream event handlers _before_ performing `send()`.

The current design is, we don't emit already-sent events when listeners are attached. I've thought about changing this to support that use-case, but I don't actually know if it's a good idea. What do you think?

**Comment by Berkmann18** [comment]
Ah okay, in fact, the console.log commands I used weren't done properly.
Well, it might be helpful especially when STDIN readers might not be "async" with the `stdin` package to the point that it would run while letting it being executed so it would receive data.
At one point, I was wondering if it kept the data sent via `send()` to a place allowing other packages/functions to read from it but visibly it doesn't; not sure if it's something other people thought.

**Comment by caitp** [comment]
The library is really intended for unit testing, so it's supposed to be as predictable as possible:

```js
function testWithStream() {
  // 1. set up stream and start consuming it
  let stream = mock_stdin();
  app.setup(stream);
  expect(module.state).toBe(kStarted);
  expect(module.step).toBe(0);

  // 2. Send some data and assert that the application is in the expected state after
  stream.send("N");
  expect(module.state).toBe(kCancelled);
  expect(module.step).toBe(0);

  // 3. Cleanup
  stream.restore();
}
```

Can you show the usage you're interested, beyond that shown above?

**Comment by Berkmann18** [comment]
Well, the usage I was interested in which brought me to this package was to "emulate" someone typing on the command line (so via the STDIN) like:
```
Some text that will was entered on the CLI to then be used to obtain a SHA256 hash for integrity checks.
This would finish before the "\$" or "\EOF" line which would be ignored in the next process.
\$
```
Which would then be read by a function (`readIn()` in my case) to process the content.

**Comment by Berkmann18** [comment]
@caitp Does that (^) aligns with the goal of the package?

**Comment by caitp** [comment]
It’s all about simulating stdin for unit testing, so yes
